package dev.sc.apm.exception;

public enum ExceptionName {
    INVALID_FIRST_NAME,
    INVALID_LAST_NAME,
    INVALID_MIDDLE_NAME,
    INVALID_PHONE,
    INVALID_PASSPORT,
    MISMATCHED_CLIENT_INFO,
    REJECTED_STATUS_DURING_SIGNING,
    PENDING_STATUS_DURING_SIGNING,
    CREDIT_APPLICATION_NOT_FOUND,
}
